apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: devops
  annotations:
    field.cattle.io/description: service
spec:
  selector:
    app: tomcat
  ports:
  - name: tomcat-first
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: tomcat-second
    port: 8090
    targetPort: 8090
    protocol: TCP
  sessionAffinity: None 
